language: python
python:
- '3.6'

cache: pip

services:
 - docker

addons:
  ssh_known_hosts:
  - 157.245.37.38

services:
- docker

before_install:
- openssl aes-256-cbc -K $encrypted_9a2873c20715_key -iv $encrypted_9a2873c20715_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/deploy_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa

before_script: pip install docker-compose

jobs:
  include:
    - stage: security
    - stage: docker-build
      script:
      - docker-compose up -d
    - stage: test
      script:
      - docker exec portfolio_portfolio_site_1 pytest
    - stage: deploy
      deploy:
      - provider: script
        skip_cleanup: true
        script: ".travis/deploy.sh"
        on:
          branch: master
