language: python
python:
- '3.6'
services:
- docker
before_script: pip install docker-compose
script:
- docker-compose build
before_install:
- openssl aes-256-cbc -K $encrypted_9a2873c20715_key -iv $encrypted_9a2873c20715_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
