language: python
python:
- '3.6'
services:
- docker
before_script: pip install docker-compose
script:
- docker-compose build
before_install:
- openssl aes-256-cbc -K $encrypted_9a2873c20715_key -iv $encrypted_9a2873c20715_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa

deploy:
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
